wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1643286546
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
aa:
  desc: null
  value: rand-m9-mstd0.5-inc1
auto_resume:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
clip_grad:
  desc: null
  value: null
color_jitter:
  desc: null
  value: 0.4
crop_pct:
  desc: null
  value: null
cutmix:
  desc: null
  value: 0.0
cutmix_minmax:
  desc: null
  value: null
data_path:
  desc: null
  value: /l/users/u21010225/AssignmentNo1/CUB/CUB_200_2011/
data_set:
  desc: null
  value: CUB
device:
  desc: null
  value: cuda
disable_eval:
  desc: null
  value: false
dist_eval:
  desc: null
  value: true
dist_on_itp:
  desc: null
  value: false
dist_url:
  desc: null
  value: env://
distributed:
  desc: null
  value: false
drop_path:
  desc: null
  value: 0.8
enable_wandb:
  desc: null
  value: false
epochs:
  desc: null
  value: 30
eval:
  desc: null
  value: false
eval_data_path:
  desc: null
  value: null
finetune:
  desc: null
  value: ./convnext_base_1k_384.pth
head_init_scale:
  desc: null
  value: 0.001
imagenet_default_mean_and_std:
  desc: null
  value: true
input_size:
  desc: null
  value: 384
layer_decay:
  desc: null
  value: 0.7
layer_scale_init_value:
  desc: null
  value: 1.0e-06
local_rank:
  desc: null
  value: -1
log_dir:
  desc: null
  value: null
lr:
  desc: null
  value: 5.0e-05
min_lr:
  desc: null
  value: 1.0e-06
mixup:
  desc: null
  value: 0.0
mixup_mode:
  desc: null
  value: batch
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
model:
  desc: null
  value: convnext_base
model_ema:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9999
model_ema_eval:
  desc: null
  value: false
model_ema_force_cpu:
  desc: null
  value: false
model_key:
  desc: null
  value: model|module
model_prefix:
  desc: null
  value: ''
momentum:
  desc: null
  value: 0.9
nb_classes:
  desc: null
  value: 200
num_workers:
  desc: null
  value: 10
opt:
  desc: null
  value: adamw
opt_betas:
  desc: null
  value: null
opt_eps:
  desc: null
  value: 1.0e-08
output_dir:
  desc: null
  value: ./
pin_mem:
  desc: null
  value: true
project:
  desc: null
  value: convnext
recount:
  desc: null
  value: 1
remode:
  desc: null
  value: pixel
reprob:
  desc: null
  value: 0.25
resplit:
  desc: null
  value: false
resume:
  desc: null
  value: ''
save_ckpt:
  desc: null
  value: true
save_ckpt_freq:
  desc: null
  value: 1
save_ckpt_num:
  desc: null
  value: 3
seed:
  desc: null
  value: 0
smoothing:
  desc: null
  value: 0.1
start_epoch:
  desc: null
  value: 0
train_interpolation:
  desc: null
  value: bicubic
update_freq:
  desc: null
  value: 2
use_amp:
  desc: null
  value: false
wandb_ckpt:
  desc: null
  value: false
warmup_epochs:
  desc: null
  value: 0
warmup_steps:
  desc: null
  value: -1
weight_decay:
  desc: null
  value: 1.0e-08
weight_decay_end:
  desc: null
  value: null
world_size:
  desc: null
  value: 1
